import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from '../config/database.js';
import User from '../models/User.js';
import Employee from '../models/Employee.js';
import SalaryPayment from '../models/SalaryPayment.js';
import Expense from '../models/Expense.js';
import Investment from '../models/Investment.js';
import Product from '../models/Product.js';
import { autoGenerateExpenseFromSalary, autoGenerateInvestmentFromStock } from '../utils/autoGeneration.js';

dotenv.config();

const testIntegration = async () => {
  try {
    await connectDB();
    console.log('🔗 Connected to database');

    // Get test user
    const user = await User.findOne({ role: 'owner' });
    if (!user) {
      console.log('❌ No owner user found. Please run seed:owner first.');
      process.exit(1);
    }
    console.log('👤 Found test user:', user.name);

    // Test 1: Auto-generate expense from salary payment
    console.log('\n📋 Test 1: Auto-generate expense from salary payment');
    
    // Find a paid salary payment
    const paidSalary = await SalaryPayment.findOne({ status: 'paid' })
      .populate('employee', 'employeeId name');
    
    if (paidSalary) {
      console.log('💰 Found paid salary:', paidSalary.employee.name, `$${paidSalary.netSalary}`);
      
      try {
        const expense = await autoGenerateExpenseFromSalary(paidSalary, user);
        console.log('✅ Auto-generated expense:', expense.expenseId, `$${expense.amount}`);
      } catch (error) {
        console.log('ℹ️  Expense may already exist:', error.message);
      }
    } else {
      console.log('ℹ️  No paid salary payments found for testing');
    }

    // Test 2: Auto-generate investment from stock purchase
    console.log('\n📈 Test 2: Auto-generate investment from stock purchase');
    
    // Find a product
    const product = await Product.findOne({ isActive: true });
    
    if (product) {
      console.log('📦 Found product:', product.name, `$${product.purchasePrice}`);
      
      try {
        // Test with a large purchase (above threshold)
        const investment = await autoGenerateInvestmentFromStock(product, 100, 150, user);
        if (investment) {
          console.log('✅ Auto-generated investment:', investment.investmentId, `$${investment.amount}`);
        } else {
          console.log('ℹ️  Investment not created (below threshold)');
        }
      } catch (error) {
        console.log('❌ Investment generation failed:', error.message);
      }
    } else {
      console.log('ℹ️  No products found for testing');
    }

    // Test 3: Check model counts
    console.log('\n📊 Test 3: Model counts');
    
    const counts = {
      users: await User.countDocuments(),
      employees: await Employee.countDocuments(),
      salaryPayments: await SalaryPayment.countDocuments(),
      expenses: await Expense.countDocuments(),
      investments: await Investment.countDocuments(),
      products: await Product.countDocuments()
    };
    
    console.log('📈 Model counts:', counts);

    // Test 4: Check auto-generated records
    console.log('\n🤖 Test 4: Auto-generated records');
    
    const autoExpenses = await Expense.countDocuments({ isAutoGenerated: true });
    const autoInvestments = await Investment.countDocuments({ isAutoGenerated: true });
    
    console.log('🔄 Auto-generated expenses:', autoExpenses);
    console.log('🔄 Auto-generated investments:', autoInvestments);

    // Test 5: Validate schema constraints
    console.log('\n✅ Test 5: Schema validation');
    
    try {
      // Test expense ID generation
      const expenseId = await Expense.generateExpenseId();
      console.log('🆔 Generated expense ID:', expenseId);
      
      // Test investment ID generation
      const investmentId = await Investment.generateInvestmentId();
      console.log('🆔 Generated investment ID:', investmentId);
      
      console.log('✅ Schema validation passed');
    } catch (error) {
      console.log('❌ Schema validation failed:', error.message);
    }

    console.log('\n🎉 Integration test completed successfully!');
    console.log('💡 All systems are working correctly');
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Integration test failed:', error);
    process.exit(1);
  }
};

testIntegration();