import mongoose from 'mongoose';

const expenseSchema = new mongoose.Schema({
  expenseId: {
    type: String,
    required: [true, 'Expense ID is required'],
    unique: true,
    trim: true,
    uppercase: true,
    match: [/^EXP-\d{6}-\d{4}$/, 'Expense ID must follow format EXP-YYYYMM-XXXX']
  },
  title: {
    type: String,
    required: [true, 'Expense title is required'],
    trim: true,
    maxlength: [200, 'Title cannot be more than 200 characters']
  },
  description: {
    type: String,
    trim: true,
    maxlength: [1000, 'Description cannot be more than 1000 characters']
  },
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: [0, 'Amount cannot be negative']
  },
  category: {
    type: String,
    required: [true, 'Category is required'],
    enum: {
      values: [
        'Salary Expense',
        'Office Rent',
        'Utilities',
        'Equipment',
        'Marketing',
        'Travel',
        'Supplies',
        'Maintenance',
        'Insurance',
        'Professional Services',
        'Other'
      ],
      message: 'Invalid expense category'
    }
  },
  subcategory: {
    type: String,
    trim: true,
    maxlength: [100, 'Subcategory cannot be more than 100 characters']
  },
  expenseDate: {
    type: Date,
    required: [true, 'Expense date is required'],
    default: Date.now
  },
  paymentMethod: {
    type: String,
    required: [true, 'Payment method is required'],
    enum: {
      values: ['cash', 'bank_transfer', 'card', 'cheque', 'upi', 'other'],
      message: 'Invalid payment method'
    },
    default: 'cash'
  },
  referenceNumber: {
    type: String,
    trim: true,
    maxlength: [100, 'Reference number cannot be more than 100 characters']
  },
  vendor: {
    name: {
      type: String,
      trim: true,
      maxlength: [200, 'Vendor name cannot be more than 200 characters']
    },
    contact: {
      type: String,
      trim: true,
      maxlength: [50, 'Vendor contact cannot be more than 50 characters']
    },
    address: {
      type: String,
      trim: true,
      maxlength: [500, 'Vendor address cannot be more than 500 characters']
    }
  },
  // Auto-generated expense tracking
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  sourceType: {
    type: String,
    enum: ['manual', 'salary', 'stock_purchase', 'invoice'],
    default: 'manual'
  },
  sourceId: {
    type: mongoose.Schema.ObjectId,
    refPath: 'sourceModel'
  },
  sourceModel: {
    type: String,
    enum: ['SalaryPayment', 'Product', 'Invoice']
  },
  // Approval workflow
  status: {
    type: String,
    enum: {
      values: ['pending', 'approved', 'rejected'],
      message: 'Status must be pending, approved, or rejected'
    },
    default: 'approved'
  },
  approvedBy: {
    type: mongoose.Schema.ObjectId,
    ref: 'User'
  },
  approvedAt: {
    type: Date
  },
  rejectionReason: {
    type: String,
    maxlength: [500, 'Rejection reason cannot be more than 500 characters']
  },
  // Attachments
  attachments: [{
    filename: {
      type: String,
      required: true
    },
    originalName: {
      type: String,
      required: true
    },
    mimeType: {
      type: String,
      required: true
    },
    size: {
      type: Number,
      required: true
    },
    uploadedAt: {
      type: Date,
      default: Date.now
    }
  }],
  // Tax information
  taxDetails: {
    isTaxable: {
      type: Boolean,
      default: false
    },
    taxRate: {
      type: Number,
      min: [0, 'Tax rate cannot be negative'],
      max: [100, 'Tax rate cannot exceed 100%'],
      default: 0
    },
    taxAmount: {
      type: Number,
      min: [0, 'Tax amount cannot be negative'],
      default: 0
    }
  },
  notes: {
    type: String,
    maxlength: [1000, 'Notes cannot be more than 1000 characters']
  },
  createdBy: {
    type: mongoose.Schema.ObjectId,
    ref: 'User',
    required: true
  },
  updatedBy: {
    type: mongoose.Schema.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

// Generate expense ID
expenseSchema.statics.generateExpenseId = async function() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const yearMonth = `${year}${month}`;
  
  // Find the last expense for this month
  const lastExpense = await this.findOne({
    expenseId: { $regex: `^EXP-${yearMonth}-` }
  }).sort({ expenseId: -1 });
  
  let sequence = 1;
  if (lastExpense) {
    const lastSequence = parseInt(lastExpense.expenseId.split('-')[2]);
    sequence = lastSequence + 1;
  }
  
  const sequenceStr = String(sequence).padStart(4, '0');
  return `EXP-${yearMonth}-${sequenceStr}`;
};

// Calculate total amount including tax
expenseSchema.virtual('totalAmount').get(function() {
  return this.amount + (this.taxDetails.taxAmount || 0);
});

// Pre-save middleware to calculate tax amount
expenseSchema.pre('save', function() {
  if (this.taxDetails.isTaxable && this.taxDetails.taxRate > 0) {
    this.taxDetails.taxAmount = (this.amount * this.taxDetails.taxRate) / 100;
  } else {
    this.taxDetails.taxAmount = 0;
  }
});

// Index for better query performance
expenseSchema.index({ expenseId: 1 });
expenseSchema.index({ expenseDate: -1 });
expenseSchema.index({ category: 1 });
expenseSchema.index({ status: 1 });
expenseSchema.index({ sourceType: 1 });
expenseSchema.index({ createdAt: -1 });

// Include virtuals when converting to JSON
expenseSchema.set('toJSON', { virtuals: true });
expenseSchema.set('toObject', { virtuals: true });

export default mongoose.model('Expense', expenseSchema);