import Expense from '../models/Expense.js';
import Investment from '../models/Investment.js';
import mongoose from 'mongoose';

/**
 * Auto-generate expense from salary payment
 * @param {Object} salaryPayment - The salary payment object
 * @param {Object} user - The user creating the expense
 * @returns {Object} Created expense
 */
export const autoGenerateExpenseFromSalary = async (salaryPayment, user) => {
  const session = await mongoose.startSession();
  session.startTransaction();

  try {
    // Check if expense already exists
    const existingExpense = await Expense.findOne({
      sourceType: 'salary',
      sourceId: salaryPayment._id
    }).session(session);

    if (existingExpense) {
      await session.abortTransaction();
      return existingExpense;
    }

    // Generate expense ID
    const expenseId = await Expense.generateExpenseId();

    // Create expense
    const expense = await Expense.create([{
      expenseId,
      title: `Salary Payment - ${salaryPayment.employee.name} (${salaryPayment.paymentMonth}/${salaryPayment.paymentYear})`,
      description: `Auto-generated expense for salary payment of ${salaryPayment.employee.name} (${salaryPayment.employee.employeeId}) for ${salaryPayment.paymentMonth}/${salaryPayment.paymentYear}`,
      amount: salaryPayment.netSalary,
      category: 'Salary Expense',
      expenseDate: salaryPayment.paymentDate || new Date(),
      paymentMethod: salaryPayment.paymentMethod,
      referenceNumber: salaryPayment.referenceNumber,
      isAutoGenerated: true,
      sourceType: 'salary',
      sourceId: salaryPayment._id,
      sourceModel: 'SalaryPayment',
      status: 'approved',
      approvedBy: user._id,
      approvedAt: new Date(),
      createdBy: user._id
    }], { session });

    // Mark salary payment as expense recorded
    await salaryPayment.updateOne(
      { isExpenseRecorded: true },
      { session }
    );

    await session.commitTransaction();
    return expense[0];
  } catch (error) {
    await session.abortTransaction();
    throw error;
  } finally {
    session.endSession();
  }
};

/**
 * Auto-generate investment from stock purchase
 * @param {Object} product - The product object
 * @param {Number} quantity - Quantity purchased
 * @param {Number} purchasePrice - Price per unit
 * @param {Object} user - The user creating the investment
 * @returns {Object} Created investment
 */
export const autoGenerateInvestmentFromStock = async (product, quantity, purchasePrice, user) => {
  const session = await mongoose.startSession();
  session.startTransaction();

  try {
    // Calculate total investment amount
    const totalAmount = quantity * purchasePrice;

    // Only create investment for significant purchases (configurable threshold)
    const INVESTMENT_THRESHOLD = 10000; // $10,000 threshold
    if (totalAmount < INVESTMENT_THRESHOLD) {
      await session.abortTransaction();
      return null; // Don't create investment for small purchases
    }

    // Generate investment ID
    const investmentId = await Investment.generateInvestmentId();

    // Create investment
    const investment = await Investment.create([{
      investmentId,
      title: `Stock Purchase - ${product.name}`,
      description: `Auto-generated investment for stock purchase of ${quantity} ${product.unit} of ${product.name} at $${purchasePrice} per ${product.unit}`,
      amount: totalAmount,
      investmentType: 'Stock Purchase',
      category: 'Operational Investment',
      investmentDate: new Date(),
      paymentMethod: 'bank_transfer',
      isAutoGenerated: true,
      sourceType: 'stock_purchase',
      sourceId: product._id,
      sourceModel: 'Product',
      status: 'approved',
      approvedBy: user._id,
      approvedAt: new Date(),
      createdBy: user._id
    }], { session });

    await session.commitTransaction();
    return investment[0];
  } catch (error) {
    await session.abortTransaction();
    throw error;
  } finally {
    session.endSession();
  }
};

/**
 * Get auto-generation statistics
 * @param {Date} startDate - Start date for filtering
 * @param {Date} endDate - End date for filtering
 * @returns {Object} Statistics object
 */
export const getAutoGenerationStats = async (startDate, endDate) => {
  try {
    const dateFilter = {};
    if (startDate || endDate) {
      dateFilter.createdAt = {};
      if (startDate) dateFilter.createdAt.$gte = startDate;
      if (endDate) dateFilter.createdAt.$lte = endDate;
    }

    // Auto-generated expenses stats
    const expenseStats = await Expense.aggregate([
      { 
        $match: { 
          isAutoGenerated: true,
          ...dateFilter
        }
      },
      {
        $group: {
          _id: '$sourceType',
          count: { $sum: 1 },
          totalAmount: { $sum: '$amount' }
        }
      }
    ]);

    // Auto-generated investments stats
    const investmentStats = await Investment.aggregate([
      { 
        $match: { 
          isAutoGenerated: true,
          ...dateFilter
        }
      },
      {
        $group: {
          _id: '$sourceType',
          count: { $sum: 1 },
          totalAmount: { $sum: '$amount' }
        }
      }
    ]);

    return {
      expenses: expenseStats,
      investments: investmentStats
    };
  } catch (error) {
    throw error;
  }
};