import mongoose from 'mongoose';
import Product from '../models/Product.js';
import Invoice from '../models/Invoice.js';
import SalaryPayment from '../models/SalaryPayment.js';
import Expense from '../models/Expense.js';
import Customer from '../models/Customer.js';

/**
 * Validate that stock quantity never goes negative
 * @param {String} productId - Product ID
 * @param {Number} quantityToDeduct - Quantity to deduct
 * @returns {Object} Validation result
 */
export const validateStockAvailability = async (productId, quantityToDeduct) => {
  try {
    const product = await Product.findById(productId);
    
    if (!product) {
      return {
        isValid: false,
        message: 'Product not found',
        currentStock: 0
      };
    }

    if (!product.isActive) {
      return {
        isValid: false,
        message: `Product ${product.name} is not active`,
        currentStock: product.stockQuantity
      };
    }

    if (product.stockQuantity < quantityToDeduct) {
      return {
        isValid: false,
        message: `Insufficient stock for ${product.name}. Available: ${product.stockQuantity}, Required: ${quantityToDeduct}`,
        currentStock: product.stockQuantity,
        required: quantityToDeduct,
        shortage: quantityToDeduct - product.stockQuantity
      };
    }

    return {
      isValid: true,
      message: 'Stock available',
      currentStock: product.stockQuantity,
      afterDeduction: product.stockQuantity - quantityToDeduct
    };
  } catch (error) {
    return {
      isValid: false,
      message: 'Error validating stock: ' + error.message,
      currentStock: 0
    };
  }
};

/**
 * Validate that due amount never goes negative
 * @param {Number} grandTotal - Invoice grand total
 * @param {Number} paidAmount - Amount being paid
 * @returns {Object} Validation result
 */
export const validatePaymentAmount = (grandTotal, paidAmount) => {
  try {
    // Ensure amounts are numbers
    const total = parseFloat(grandTotal) || 0;
    const paid = parseFloat(paidAmount) || 0;

    if (paid < 0) {
      return {
        isValid: false,
        message: 'Paid amount cannot be negative',
        adjustedPaidAmount: 0
      };
    }

    if (paid > total) {
      return {
        isValid: true,
        message: 'Payment amount exceeds total, will be capped at grand total',
        adjustedPaidAmount: total,
        dueAmount: 0,
        status: 'paid'
      };
    }

    const dueAmount = total - paid;
    let status = 'due';
    
    if (paid === 0) {
      status = 'due';
    } else if (paid >= total) {
      status = 'paid';
    } else {
      status = 'partial';
    }

    return {
      isValid: true,
      message: 'Payment amount is valid',
      adjustedPaidAmount: paid,
      dueAmount: Math.max(0, dueAmount),
      status
    };
  } catch (error) {
    return {
      isValid: false,
      message: 'Error validating payment: ' + error.message,
      adjustedPaidAmount: 0
    };
  }
};

/**
 * Ensure salary payment always creates an expense when marked as paid
 * @param {Object} salaryPayment - Salary payment object
 * @param {Object} user - User marking salary as paid
 * @returns {Object} Validation and creation result
 */
export const ensureSalaryExpenseCreation = async (salaryPayment, user) => {
  const session = await mongoose.startSession();
  
  try {
    await session.withTransaction(async () => {
      // Check if expense already exists
      const existingExpense = await Expense.findOne({
        sourceType: 'salary',
        sourceId: salaryPayment._id
      }).session(session);

      if (existingExpense) {
        return {
          success: true,
          message: 'Expense already exists',
          expense: existingExpense,
          created: false
        };
      }

      // Generate expense ID
      const expenseId = await Expense.generateExpenseId();

      // Create expense
      const expense = await Expense.create([{
        expenseId,
        title: `Salary Payment - ${salaryPayment.employee.name} (${salaryPayment.paymentMonth}/${salaryPayment.paymentYear})`,
        description: `Auto-generated expense for salary payment of ${salaryPayment.employee.name} (${salaryPayment.employee.employeeId}) for ${salaryPayment.paymentMonth}/${salaryPayment.paymentYear}`,
        amount: salaryPayment.netSalary,
        category: 'Salary Expense',
        expenseDate: salaryPayment.paymentDate || new Date(),
        paymentMethod: salaryPayment.paymentMethod || 'bank_transfer',
        referenceNumber: salaryPayment.referenceNumber,
        isAutoGenerated: true,
        sourceType: 'salary',
        sourceId: salaryPayment._id,
        sourceModel: 'SalaryPayment',
        status: 'approved',
        approvedBy: user._id,
        approvedAt: new Date(),
        createdBy: user._id
      }], { session });

      // Mark salary payment as expense recorded
      await SalaryPayment.findByIdAndUpdate(
        salaryPayment._id,
        { isExpenseRecorded: true },
        { session }
      );

      return {
        success: true,
        message: 'Expense created successfully',
        expense: expense[0],
        created: true
      };
    });
  } catch (error) {
    throw new Error('Failed to create salary expense: ' + error.message);
  } finally {
    await session.endSession();
  }
};

/**
 * Restore stock when invoice is cancelled or returned
 * @param {Object} invoice - Invoice object
 * @param {Object} user - User performing the action
 * @returns {Object} Restoration result
 */
export const restoreInvoiceStock = async (invoice, user) => {
  const session = await mongoose.startSession();
  
  try {
    const restorationResults = [];
    
    await session.withTransaction(async () => {
      for (const item of invoice.items) {
        const product = await Product.findById(item.product).session(session);
        
        if (product) {
          const oldStock = product.stockQuantity;
          product.stockQuantity += item.quantity;
          product.updatedBy = user._id;
          await product.save({ session });
          
          restorationResults.push({
            productId: product._id,
            productName: product.name,
            quantityRestored: item.quantity,
            oldStock,
            newStock: product.stockQuantity
          });
        } else {
          restorationResults.push({
            productId: item.product,
            productName: item.productName,
            quantityRestored: item.quantity,
            error: 'Product not found'
          });
        }
      }
    });

    return {
      success: true,
      message: 'Stock restored successfully',
      restorations: restorationResults
    };
  } catch (error) {
    return {
      success: false,
      message: 'Failed to restore stock: ' + error.message,
      restorations: []
    };
  } finally {
    await session.endSession();
  }
};

/**
 * Validate customer due balances match invoice dues
 * @param {String} customerId - Customer ID to validate
 * @returns {Object} Validation result
 */
export const validateCustomerDueBalance = async (customerId) => {
  try {
    const customer = await Customer.findById(customerId);
    if (!customer) {
      return {
        isValid: false,
        message: 'Customer not found'
      };
    }

    // Calculate actual due from invoices
    const invoiceTotals = await Invoice.aggregate([
      {
        $match: {
          customer: new mongoose.Types.ObjectId(customerId),
          isActive: true
        }
      },
      {
        $group: {
          _id: null,
          totalSales: { $sum: '$grandTotal' },
          totalPaid: { $sum: '$paidAmount' },
          totalDue: { $sum: '$dueAmount' },
          invoiceCount: { $sum: 1 }
        }
      }
    ]);

    const actualTotals = invoiceTotals[0] || {
      totalSales: 0,
      totalPaid: 0,
      totalDue: 0,
      invoiceCount: 0
    };

    // Check if customer totals match invoice totals
    const salesMatch = Math.abs(customer.totalSales - actualTotals.totalSales) < 0.01;
    const paidMatch = Math.abs(customer.totalPaid - actualTotals.totalPaid) < 0.01;
    const dueMatch = Math.abs(customer.totalDue - actualTotals.totalDue) < 0.01;
    const countMatch = customer.invoiceCount === actualTotals.invoiceCount;

    const isValid = salesMatch && paidMatch && dueMatch && countMatch;

    return {
      isValid,
      message: isValid ? 'Customer totals match invoice totals' : 'Customer totals do not match invoice totals',
      customerTotals: {
        totalSales: customer.totalSales,
        totalPaid: customer.totalPaid,
        totalDue: customer.totalDue,
        invoiceCount: customer.invoiceCount
      },
      actualTotals,
      mismatches: {
        sales: !salesMatch ? { customer: customer.totalSales, actual: actualTotals.totalSales } : null,
        paid: !paidMatch ? { customer: customer.totalPaid, actual: actualTotals.totalPaid } : null,
        due: !dueMatch ? { customer: customer.totalDue, actual: actualTotals.totalDue } : null,
        count: !countMatch ? { customer: customer.invoiceCount, actual: actualTotals.invoiceCount } : null
      }
    };
  } catch (error) {
    return {
      isValid: false,
      message: 'Error validating customer due balance: ' + error.message
    };
  }
};
export const validateCalculations = (data, type) => {
  try {
    const result = {
      isValid: true,
      corrections: [],
      originalData: { ...data },
      correctedData: { ...data }
    };

    switch (type) {
      case 'invoice':
        return validateInvoiceCalculations(data, result);
      case 'salary':
        return validateSalaryCalculations(data, result);
      case 'profit':
        return validateProfitCalculations(data, result);
      default:
        return {
          isValid: false,
          message: 'Unknown calculation type'
        };
    }
  } catch (error) {
    return {
      isValid: false,
      message: 'Error validating calculations: ' + error.message
    };
  }
};

/**
 * Validate invoice calculations
 */
const validateInvoiceCalculations = (data, result) => {
  const { items, discount = 0, discountType = 'amount' } = data;
  
  // Calculate subtotal from items
  const calculatedSubtotal = items.reduce((sum, item) => {
    const itemTotal = (parseFloat(item.quantity) || 0) * (parseFloat(item.unitPrice) || 0);
    if (Math.abs(itemTotal - (parseFloat(item.totalPrice) || 0)) > 0.01) {
      result.corrections.push({
        field: `items[${items.indexOf(item)}].totalPrice`,
        expected: itemTotal,
        actual: item.totalPrice,
        message: 'Item total price mismatch'
      });
      result.correctedData.items[items.indexOf(item)].totalPrice = itemTotal;
    }
    return sum + itemTotal;
  }, 0);

  // Validate subtotal
  if (Math.abs(calculatedSubtotal - (parseFloat(data.subtotal) || 0)) > 0.01) {
    result.corrections.push({
      field: 'subtotal',
      expected: calculatedSubtotal,
      actual: data.subtotal,
      message: 'Subtotal mismatch'
    });
    result.correctedData.subtotal = calculatedSubtotal;
  }

  // Calculate discount amount
  let discountAmount = 0;
  if (discountType === 'percentage') {
    discountAmount = (calculatedSubtotal * parseFloat(discount)) / 100;
  } else {
    discountAmount = parseFloat(discount) || 0;
  }

  // Calculate grand total
  const calculatedGrandTotal = Math.max(0, calculatedSubtotal - discountAmount);
  if (Math.abs(calculatedGrandTotal - (parseFloat(data.grandTotal) || 0)) > 0.01) {
    result.corrections.push({
      field: 'grandTotal',
      expected: calculatedGrandTotal,
      actual: data.grandTotal,
      message: 'Grand total mismatch'
    });
    result.correctedData.grandTotal = calculatedGrandTotal;
  }

  // Validate due amount
  const paidAmount = Math.min(parseFloat(data.paidAmount) || 0, calculatedGrandTotal);
  const calculatedDueAmount = Math.max(0, calculatedGrandTotal - paidAmount);
  
  if (Math.abs(calculatedDueAmount - (parseFloat(data.dueAmount) || 0)) > 0.01) {
    result.corrections.push({
      field: 'dueAmount',
      expected: calculatedDueAmount,
      actual: data.dueAmount,
      message: 'Due amount mismatch'
    });
    result.correctedData.dueAmount = calculatedDueAmount;
  }

  // Validate paid amount doesn't exceed grand total
  if (parseFloat(data.paidAmount) > calculatedGrandTotal) {
    result.corrections.push({
      field: 'paidAmount',
      expected: calculatedGrandTotal,
      actual: data.paidAmount,
      message: 'Paid amount exceeds grand total'
    });
    result.correctedData.paidAmount = calculatedGrandTotal;
    result.correctedData.dueAmount = 0;
  }

  result.isValid = result.corrections.length === 0;
  return result;
};

/**
 * Validate salary calculations
 */
const validateSalaryCalculations = (data, result) => {
  const { baseSalary, allowances = {}, deductions = {}, overtime = {} } = data;
  
  // Calculate total allowances
  const calculatedAllowances = (parseFloat(allowances.hra) || 0) +
                              (parseFloat(allowances.transport) || 0) +
                              (parseFloat(allowances.medical) || 0) +
                              (parseFloat(allowances.other) || 0);

  // Calculate overtime amount
  const calculatedOvertimeAmount = (parseFloat(overtime.hours) || 0) * (parseFloat(overtime.rate) || 0);
  if (Math.abs(calculatedOvertimeAmount - (parseFloat(overtime.amount) || 0)) > 0.01) {
    result.corrections.push({
      field: 'overtime.amount',
      expected: calculatedOvertimeAmount,
      actual: overtime.amount,
      message: 'Overtime amount mismatch'
    });
    result.correctedData.overtime.amount = calculatedOvertimeAmount;
  }

  // Calculate gross salary
  const calculatedGrossSalary = (parseFloat(baseSalary) || 0) + calculatedAllowances + calculatedOvertimeAmount;
  if (Math.abs(calculatedGrossSalary - (parseFloat(data.grossSalary) || 0)) > 0.01) {
    result.corrections.push({
      field: 'grossSalary',
      expected: calculatedGrossSalary,
      actual: data.grossSalary,
      message: 'Gross salary mismatch'
    });
    result.correctedData.grossSalary = calculatedGrossSalary;
  }

  // Calculate total deductions
  const calculatedDeductions = (parseFloat(deductions.pf) || 0) +
                              (parseFloat(deductions.esi) || 0) +
                              (parseFloat(deductions.tax) || 0) +
                              (parseFloat(deductions.advance) || 0) +
                              (parseFloat(deductions.other) || 0);

  if (Math.abs(calculatedDeductions - (parseFloat(data.totalDeductions) || 0)) > 0.01) {
    result.corrections.push({
      field: 'totalDeductions',
      expected: calculatedDeductions,
      actual: data.totalDeductions,
      message: 'Total deductions mismatch'
    });
    result.correctedData.totalDeductions = calculatedDeductions;
  }

  // Calculate net salary (ensure it's not negative)
  const calculatedNetSalary = Math.max(0, calculatedGrossSalary - calculatedDeductions);
  if (Math.abs(calculatedNetSalary - (parseFloat(data.netSalary) || 0)) > 0.01) {
    result.corrections.push({
      field: 'netSalary',
      expected: calculatedNetSalary,
      actual: data.netSalary,
      message: 'Net salary mismatch'
    });
    result.correctedData.netSalary = calculatedNetSalary;
  }

  result.isValid = result.corrections.length === 0;
  return result;
};

/**
 * Validate profit calculations
 */
const validateProfitCalculations = (data, result) => {
  const { totalSales, productCosts, salaryExpenses, otherExpenses } = data;
  
  // Calculate total costs
  const calculatedTotalCosts = (parseFloat(productCosts) || 0) + 
                              (parseFloat(salaryExpenses) || 0) + 
                              (parseFloat(otherExpenses) || 0);

  if (Math.abs(calculatedTotalCosts - (parseFloat(data.totalCosts) || 0)) > 0.01) {
    result.corrections.push({
      field: 'totalCosts',
      expected: calculatedTotalCosts,
      actual: data.totalCosts,
      message: 'Total costs mismatch'
    });
    result.correctedData.totalCosts = calculatedTotalCosts;
  }

  // Calculate net profit
  const calculatedNetProfit = (parseFloat(totalSales) || 0) - calculatedTotalCosts;
  if (Math.abs(calculatedNetProfit - (parseFloat(data.netProfit) || 0)) > 0.01) {
    result.corrections.push({
      field: 'netProfit',
      expected: calculatedNetProfit,
      actual: data.netProfit,
      message: 'Net profit mismatch'
    });
    result.correctedData.netProfit = calculatedNetProfit;
  }

  // Calculate profit margin
  const calculatedProfitMargin = parseFloat(totalSales) > 0 ? 
    (calculatedNetProfit / parseFloat(totalSales)) * 100 : 0;
  
  if (Math.abs(calculatedProfitMargin - (parseFloat(data.profitMargin) || 0)) > 0.01) {
    result.corrections.push({
      field: 'profitMargin',
      expected: calculatedProfitMargin,
      actual: data.profitMargin,
      message: 'Profit margin mismatch'
    });
    result.correctedData.profitMargin = calculatedProfitMargin;
  }

  result.isValid = result.corrections.length === 0;
  return result;
};

/**
 * Run comprehensive business validation checks
 * @returns {Object} Validation report
 */
export const runBusinessValidationChecks = async () => {
  const report = {
    timestamp: new Date(),
    checks: [],
    summary: {
      total: 0,
      passed: 0,
      failed: 0,
      warnings: 0
    }
  };

  try {
    // Check for negative stock quantities
    const negativeStockProducts = await Product.find({ stockQuantity: { $lt: 0 } });
    report.checks.push({
      name: 'Negative Stock Check',
      status: negativeStockProducts.length === 0 ? 'PASS' : 'FAIL',
      message: negativeStockProducts.length === 0 ? 
        'No products with negative stock found' : 
        `Found ${negativeStockProducts.length} products with negative stock`,
      details: negativeStockProducts.map(p => ({
        productId: p._id,
        name: p.name,
        stock: p.stockQuantity
      }))
    });

    // Check for negative due amounts
    const negativeDueInvoices = await Invoice.find({ dueAmount: { $lt: 0 } });
    report.checks.push({
      name: 'Negative Due Amount Check',
      status: negativeDueInvoices.length === 0 ? 'PASS' : 'FAIL',
      message: negativeDueInvoices.length === 0 ? 
        'No invoices with negative due amounts found' : 
        `Found ${negativeDueInvoices.length} invoices with negative due amounts`,
      details: negativeDueInvoices.map(i => ({
        invoiceId: i._id,
        invoiceNo: i.invoiceNo,
        dueAmount: i.dueAmount
      }))
    });

    // Check for paid salaries without expenses
    const paidSalariesWithoutExpenses = await SalaryPayment.find({
      status: 'paid',
      isExpenseRecorded: { $ne: true }
    }).populate('employee', 'name employeeId');

    report.checks.push({
      name: 'Salary Expense Recording Check',
      status: paidSalariesWithoutExpenses.length === 0 ? 'PASS' : 'WARNING',
      message: paidSalariesWithoutExpenses.length === 0 ? 
        'All paid salaries have corresponding expenses' : 
        `Found ${paidSalariesWithoutExpenses.length} paid salaries without expense records`,
      details: paidSalariesWithoutExpenses.map(s => ({
        salaryId: s._id,
        employeeName: s.employee.name,
        employeeId: s.employee.employeeId,
        month: s.paymentMonth,
        year: s.paymentYear,
        amount: s.netSalary
      }))
    });

    // Check customer due balance consistency
    const customersWithMismatchedTotals = [];
    const customers = await Customer.find({ isActive: true }).limit(100); // Check first 100 customers
    
    for (const customer of customers) {
      const validation = await validateCustomerDueBalance(customer._id);
      if (!validation.isValid) {
        customersWithMismatchedTotals.push({
          customerId: customer.customerId,
          customerName: customer.name,
          mismatches: validation.mismatches
        });
      }
    }

    report.checks.push({
      name: 'Customer Due Balance Check',
      status: customersWithMismatchedTotals.length === 0 ? 'PASS' : 'WARNING',
      message: customersWithMismatchedTotals.length === 0 ? 
        'All customer totals match invoice totals' : 
        `Found ${customersWithMismatchedTotals.length} customers with mismatched totals`,
      details: customersWithMismatchedTotals
    });

    // Check for calculation mismatches in recent invoices
    const recentInvoices = await Invoice.find({
      createdAt: { $gte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) }
    }).limit(100);

    let calculationMismatches = 0;
    for (const invoice of recentInvoices) {
      const validation = validateCalculations(invoice.toObject(), 'invoice');
      if (!validation.isValid) {
        calculationMismatches++;
      }
    }

    report.checks.push({
      name: 'Invoice Calculation Check',
      status: calculationMismatches === 0 ? 'PASS' : 'WARNING',
      message: calculationMismatches === 0 ? 
        'All recent invoice calculations are correct' : 
        `Found ${calculationMismatches} invoices with calculation mismatches`,
      details: { checkedInvoices: recentInvoices.length, mismatches: calculationMismatches }
    });

    // Calculate summary
    report.summary.total = report.checks.length;
    report.summary.passed = report.checks.filter(c => c.status === 'PASS').length;
    report.summary.failed = report.checks.filter(c => c.status === 'FAIL').length;
    report.summary.warnings = report.checks.filter(c => c.status === 'WARNING').length;

    return report;
  } catch (error) {
    report.checks.push({
      name: 'Validation System Check',
      status: 'FAIL',
      message: 'Error running validation checks: ' + error.message
    });
    return report;
  }
};

export default {
  validateStockAvailability,
  validatePaymentAmount,
  ensureSalaryExpenseCreation,
  restoreInvoiceStock,
  validateCalculations,
  validateCustomerDueBalance,
  runBusinessValidationChecks
};